{% set name = "datalad-installer" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eb7240496e51d59ac045f2a0125641c7bbe6305a794e4e4f629fbc34f7967d7f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - datalad-installer = datalad_installer:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6

test:
  requires:
    - bash  # [not win]
    - git  # Needed for testing `datalad --help` after installation
    - pytest
    - pytest-cov
    - pytest-mock
  files:
    - test.bat
    - test.sh
  source_files:
    - test
    - tox.ini
  imports:
    - datalad_installer
  commands:
    - bash test.sh  # [not win]
    - test.bat  # [win]

about:
  home: https://github.com/datalad/datalad-installer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Installation script for Datalad and related components
  description: |
    `datalad-installer` is a script for installing Datalad, git-annex, and
    related components all in a single invocation.  It requires no third-party
    Python libraries, though it does make heavy use of external packaging
    commands.
  dev_url: https://github.com/datalad/datalad-installer

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
